- name: "upload vault ufw config file"
  template:                                                                                                               
    src: ufw/ports.j2                          
    dest: /etc/ufw/applications.d/vault                                                                     
    decrypt: yes
    force: yes
            
- name: "set default ufw policy to DENY"  
  command: "ufw default deny"     

- name: "allow outgoing connection"       
  command: "ufw default allow outgoing" 

- name: "open ssh port"               
  command: "ufw allow 22/tcp"    

- name: "open DNS port"              
  command: "ufw allow 53"  

- name: "enabling ufw rule"
  command: "ufw allow 'vault'"

- name: "ensure ufw is enabled"  
  command: "ufw --force enable"

- name: "reload ufw"                                                             
  command: "ufw reload"