- name: Upload Vault Systemd Service File
  template:
    src: service/vault.service.j2
    dest: "{{systemd_unit_directory}}/vault.service"
    owner: "{{vault_user}}"
    group: "{{vault_group}}"
    force: yes
  register: vault_service
  
- name: Confirm Destination of Systemd File
  debug:
    msg: successfully uploaded
  when: vault_service is succeeded

- name: Enable Vault Service
  service:
    name: vault
    state: stopped
    enabled: yes
  when: vault_service is changed

- name: Populate Service Facts
  service_facts:

- name: Print Vault Status
  debug:
    var: ansible_facts.services['vault.service'].status