- name: Ensure firewalld service is disabled and stopped
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  notify: 
  - Populate Service Facts
  - Print Firewalld Status

- name: Copy iptables file
  copy:
    src: files/iptables
    dest: "/etc/sysconfig/iptables"
    owner: "root"
    group: "root"
    mode: 0600
  register: iptables_file

- name: Confirm iptables_file was copied
  debug:
    msg: successfully copied
  when: iptables_file is succeeded

- name: Copy content to rc.local file
  lineinfile:
    line: sudo iptables-restore < /etc/sysconfig/iptables
    path: /etc/rc.local
  register: iptables_restore

- name: Confirm content was copied to rc.local file
  debug:
    msg: successfully copied
  when: iptables_restore is succeeded

- name: Add execute permision to rc.local file
  command: "chmod +x /etc/rc.local"
  register: rc_local

- name: Confirm rc.local permission changed
  debug:
    msg: successfully executed
  when: rc_local is succeeded
