- name: Create Directory for Vault Config Templates
  file:
    path: "{{ vault_config_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0700
    recurse: true
  register: config_dir

- name: Confirm Creation of Vault Config Directory
  debug:
    msg: successfully created
  when: config_dir is succeeded

- name: Upload Vault Listener Template
  template:
    src: config/listener.hcl.j2
    dest: "{{ vault_config_path }}/listener.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0700
    force: true
  register: vault_listener

- name: Confirm Destination of Vault Listener Template
  debug:
    msg: successfully uploaded
  when: vault_listener is succeeded
