- name: Download Goss
  get_url:
    url: "{{ goss_bin_src }}"
    dest: "{{ goss_bin_dest }}"
    owner: root
    group: root
    force: yes
    mode: 0555
  register: goss_download

- name: Confirm Goss is Downloaded
  debug:
    msg: binary successfully downloaded
  when: goss_download is succeeded