- name: Install Packages
  yum:
    name: "{{packages}}"
    state: present
  vars:  
    packages:
    - zip
    - unzip
    - gzip
    - jq
    - curl
    - wget
    update_cache: true

- name: Update Packages
  yum:
    name: "*"
    state: latest
    update_cache: true